version: "3"

services:
  app:
    container_name: app
    hostname: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-networks

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
