version: "3"

services:
  app:
    image: thelucasliao/openlock-staging-app:latest
    container_name: app
    hostname: app
    ports:
      - "3000:3000"
    networks:
      - app-networks

  nginx:
    image: thelucasliao/openlock-staging-nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
